---
# general
post_to_api: True
wait_time: True
coordinates_name_file: "data/200624_Bahnhofsliste.csv"
copy_ratio: 0.3
identifier: "0042"

# map
shapefile: "data/shape_germany"
show_map: False
save_map: False

run1:
  time: "08:54"
  city_types:
    - "Großstadtknoten"
  city_names:
    - "Rostock, Hansestadt"
  num_samples: 54
  location_randomization: 0.1
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False

run2:
  time: "09:32"
  city_types:
    - "Großstadtknoten"
    - "Regionaler Knoten"
    - "Regionaler Zubringer"
  city_names:
    - "Rostock, Hansestadt"
  num_samples: 94
  location_randomization: 0.03
  geo_barrier:
    lat_neg: False
    lat_pos: True
    lon_neg: False
    lon_pos: False

run3:
  time: "10:12"
  city_types:
    - "Großstadtknoten"
  city_names:
    - "Lübeck, Hansestadt"
  num_samples: 173
  location_randomization: 0.08
  geo_barrier:
    lat_neg: False
    lat_pos: True
    lon_neg: False
    lon_pos: True

run4:
  time: "10:14"
  city_types:
    - "Regionaler Knoten"
  city_names:
    - "Flensburg, Stadt"
  num_samples: 69
  location_randomization: 0.2
  geo_barrier:
    lat_neg: False
    lat_pos: True
    lon_neg: False
    lon_pos: False

run5:
  time: "10:17"
  city_types:
    - "Regionaler Zubringer"
  city_names:
    - "Neubrandenburg, Stadt"
  num_samples: 72
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False


run6:
  time: "11:01"
  city_types:
    - "ländlicher Zubringer"
    - "Regionaler Zubringer"
  city_names:
    - "Bielefeld, Stadt"
    - "Osnabrück, Stadt"
  num_samples: 61
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False


run7:
  time: "11:32"
  city_types:
    - "Regionaler Zubringer"
    - "Regionaler Knoten"
  city_names:
    - "Paderborn, Stadt"
    - "Celle, Stadt"
  num_samples: 51
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False


run8:
  time: "12:26"
  city_types:
    - "Metropolbahnhof"
    - "Zentraler S-Bahnhof"
    - "Großstadtknoten"
  city_names:
    - "Hannover, Landeshauptstadt"
    - "Berlin, Stadt"
    - "Leipzig, Stadt"
  num_samples: 958
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False


run9:
  time: "13:01"
  city_types:
    - "Regionaler Zubringer"
  city_names:
    - "Braunschweig, Stadt"
  num_samples: 57
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False

run10:
  time: "15:03"
  city_types:
    - "Metropolbahnhof"
    - "Zentraler S-Bahnhof"
    - "Regionaler Zubringer"
  city_names:
    - "Essen, Stadt"
    - "Dortmund, Stadt"
    - "Berlin, Stadt"
    - "Hannover, Landeshauptstadt"
  num_samples: 754
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False

run11:
  time: "17:37"
  city_types:
    - "Metropolbahnhof"
    - "Zentraler S-Bahnhof"
    - "Regionaler Zubringer"
    - "Grossstadtknoten"
  city_names:
    - "Frankfurt am Main, Stadt"
  num_samples: 528
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False

run12:
  time: "18:01"
  city_types:
    - "Regionaler Zubringer"
  city_names:
    - "Würzburg"
    - "Nürnberg"
  num_samples: 122
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False

run13:
  time: "18:32"
  city_types:
    - "Metropolbahnhof"
    - "Regionaler Zubringer"
  city_names:
    - "Mannheim, Universitätsstadt"
  num_samples: 57
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False

run14:
  time: "18:59"
  city_types:
    - "Regionaler Zubringer"
  city_names:
    - "Stuttgart, Landeshauptstadt"
  num_samples: 57
  location_randomization: 0.3
  geo_barrier:
    lat_neg: False
    lat_pos: False
    lon_neg: False
    lon_pos: False
